FROM grafana/grafana

USER grafana

ARG GF_INSTALL_PLUGINS="grafana-timestream-datasource grafana-iot-sitewise-datasource grafana-azure-data-explorer-datasource grafana-azure-monitor-datasource grafana-discourse-datasource grafana-github-datasource grafana-googlesheets-datasource grafana-k6cloud-datasource grafana-kairosdb-datasource grafana-es-open-distro-datasource grafana-opensearch-datasource grafana-simple-json-datasource grafana-strava-datasource grafana-x-ray-datasource grafana-synthetic-monitoring-app grafana-worldmap-panel grafana-clock-panel grafana-piechart-panel grafana-polystat-panel grafana-singlestat-panel akumuli-datasource praj-ams-datasource anodot-datasource hadesarchitect-cassandra-datasource thalysantana-appcenter-datasource rackerlabs-blueflood-datasource bmchelix-ade-datasource yeya24-chaosmesh-datasource vertamedia-clickhouse-datasource foursquare-clouderamanager-datasource cognitedata-datasource sbueringer-consul-datasource marcusolsson-csv-datasource dalmatinerdb-datasource andig-darksky-datasource devicehive-devicehive-datasource abhisant-druid-datasource grafadruid-druid-datasource ayoungprogrammer-finance-datasource clarity89-finnhub-datasource verticle-flowhook-datasource gnocchixyz-gnocchi-datasource doitintl-bigquery-datasource mtanda-google-calendar-datasource fifemon-graphql-datasource groonga-datasource hawkular-datasource udoprog-heroic-datasource spotify-heroic-datasource humio-datasource ibm-apm-datasource yesoreyeram-infinity-datasource instana-datasource itrs-hub-datasource simpod-json-datasource marcusolsson-json-datasource paytm-kapacitor-datasource aquaqanalytics-kdbadaptor-datasource lightstep-metrics-datasource linksmart-hds-datasource linksmart-sensorthings-datasource goshposh-metaqueries-datasource meteostat-meteostat-datasource monasca-datasource monitoringartist-monitoringart-datasource radensolutions-netxms-datasource ntop-ntopng-datasource fastweb-openfalcon-datasource gridprotectionalliance-openhistorian-datasource oci-logs-datasource oci-metrics-datasource gridprotectionalliance-osisoftpi-datasource xginn8-pagerduty-datasource pixie-pixie-datasource sni-pnp-datasource camptocamp-prometheus-alertmanager-datasource jasonlashua-prtg-datasource pyroscope-datasource quasardb-datasource redis-datasource ccin2p3-riemann-datasource sidewinder-datasource fzakaria-simple-annotations-datasource innius-grpc-datasource skydive-datasource pue-solr-datasource frser-sqlite-datasource marcusolsson-static-datasource streamr-datasource fetzerch-sunandmoon-datasource teamviewer-datasource sni-thruk-datasource natel-usgs-datasource vertica-grafana-datasource ovh-warp10-datasource alexanderzobnin-zabbix-app voxter-app percona-percona-app bosun-app devopsprodigy-kubegraf-app ddurieux-glpi-app opennms-helm-app stagemonitor-elasticsearch-app"

RUN if [ ! -z "${GF_INSTALL_PLUGINS}" ]; then \
    OLDIFS=$IFS; \
        IFS=','; \
    for plugin in ${GF_INSTALL_PLUGINS}; do \
        IFS=$OLDIFS; \
        grafana-cli --pluginsDir "$GF_PATHS_PLUGINS" plugins install ${plugin}; \
    done; \
fi